### ISSUE TITLE
Latest FeedBack

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#1094]
https://steemit.com/esteem/@bala41288/reviewing-new-2-2-0-version-of-esteem-application-good-and-bad

===========

- Can't play Dtube and Youtube Video
- Right and Left align items do not display perfectly
- click comment vote list doesn't work

<img src="https://i.ibb.co/R0PwZSw/Screenshot-2019-08-27-06-59-49.png" alt="Screenshot-2019-08-27-06-59-49" border="0">

***
<img src="https://i.ibb.co/pw6QZDR/Screenshot-2019-08-27-06-52-53.png" alt="Screenshot-2019-08-27-06-52-53" border="0">
***
<img src="https://i.ibb.co/J3nPNHM/Screenshot-2019-08-27-06-50-01.png" alt="Screenshot-2019-08-27-06-50-01" border="0">

***
Heading space before and after text is too much
<img src="https://i.ibb.co/f0cvGQh/Screenshot-2019-08-27-06-23-33.png" alt="Screenshot-2019-08-27-06-23-33" border="0">

***
Images in table display weird; from the announcement post
<img src="https://i.ibb.co/FwPdLPq/Screenshot-2019-08-27-14-55-40.png" alt="Screenshot-2019-08-27-14-55-40" border="0">

**Comment by feruzm** [comment]
We have fixed all reported bugs in post. Update is pushed to PlayStore, in few hours everyone will have update

**Comment by horpeyloaded** [comment]
Incredible, heading to the moon! 
Will update some bugs I found if they've not been fixed in the latest update. 
🏃

**Comment by horpeyloaded** [comment]
- Can't play Dtube and Youtube Video
- Right and Left align items do not display perfectly

<img src="https://i.ibb.co/R0PwZSw/Screenshot-2019-08-27-06-59-49.png" alt="Screenshot-2019-08-27-06-59-49" border="0">
<img src="https://i.ibb.co/pw6QZDR/Screenshot-2019-08-27-06-52-53.png" alt="Screenshot-2019-08-27-06-52-53" border="0">
<img src="https://i.ibb.co/J3nPNHM/Screenshot-2019-08-27-06-50-01.png" alt="Screenshot-2019-08-27-06-50-01" border="0">

Heading space before and after text is too much
<img src="https://i.ibb.co/f0cvGQh/Screenshot-2019-08-27-06-23-33.png" alt="Screenshot-2019-08-27-06-23-33" border="0">
