### ISSUE TITLE
Suggestion on Ponits

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#1183]
I don't think this will be taken though 

Points Reward system as was modified to be dynamic and/or to change based on user activity, should have the amounts refreshed in order to reflect the user benefits in order to offer clear information to the end user.

**Comment by feruzm** [comment]
Do you mean updating tooltips information?

**Comment by horpeyloaded** [comment]
Yeah, the user 👥 mean tooltips
