### ISSUE TITLE
eSteem app froze!

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1253]
I was creating a new post and everything froze up on the app

I couldn't grab a screenshot, It did pop up with three options:  close the app, wait or send an error report. I chose the option to wait twice, then sent the error report, and finally closed the app. Thankfully most of the post was saved when I reopened the app. Hope this helps!

https://cdn.discordapp.com/attachments/385448634197737484/639777633726627840/Screenshot_20191101-054703_Device_care.jpg

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@horpey` in `#📲-esteem-mobile`.

**Comment by mistikk** [comment]
it is related with #820 #1144
