### ISSUE TITLE
Make user quickly powerup

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#1255]
Some users have long usernames, users retyping it in the username box takes some secs. I suggest a shortcut that quickly fill in the user's username. May be when username placehold is clicked, it should replace it with user's username. 

 ![](https://i.ibb.co/RcrKFdx/Screenshot-2019-11-01-23-20-38.png)

**Comment by feruzm** [comment]
Yes, 👍 Plus remove memo field from power up screen

**Comment by mistikk** [comment]
just for power up screen or all of wallet actions pages @feruzm @horpeyloaded

**Comment by feruzm** [comment]
@mistikk just power up page.
