### ISSUE TITLE
DTUBE, YouTube and Appics Post

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1269]
There are problems with posts related to the mentioned apps. I know it's has been already been reported but please don't forget to fix them in next release.

- Appics
- Dtube
- YouTube

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@horpey` in `#📲-esteem-mobile`.

**Comment by horpeyloaded** [comment]
YouTube link only displays its thumbnail but can't play it.

Dtube post:
https://esteem.app/dtube/@appics/52oscjqzlyl, Display thumbnail twice, and Thumbnail is not same as Steemit
