### ISSUE TITLE
Flagged Posts

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1420]
I suggest downvote value should be the first on the upvote list like other STEEM UIs, or can we have another tab for downvote list

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@horpey` in `#📲-esteem-mobile`.

**Comment by horpeyloaded** [comment]
I can see this was implemented. I will reopen if not

**Comment by feruzm** [comment]
There is already sorting within voters page. We can however think on improving it to sort other way around as well.
