### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cybermom** [ecency/ecency-mobile#1750]
### <center> The "save draft" button feature is does not function as designed when creating a new post using the latest version of the Ecency app from my Samsung Galaxy Note 8 smartphone. 

I clicked on the save draft icon while creating a new post but none of the new content or subsequent changes were stored. None of the tags stick either -- it comes up blank. 

I went to look at my saved drafts a moment ago and they are totally blank. Ultimately I had to surrender and use Peakd to post. Please handle. </center>

**Comment by feruzm** [comment]
Thank you for report. We are preparing new release as we speak, will make sure to include fix.

**Comment by Cybermom** [comment]
Thank you very much! Thought I'd use the link on the latest Ecency post instead of messaging on Discord. I'll check things after the latest update is installed.😉👍😀On Aug 5, 2020 12:26 AM, Feruz M <notifications@github.com> wrote:
Thank you for report. We are preparing new release as we speak, will make sure to include fix.

**Comment by feruzm** [comment]
@Cybermom please check latest update and let us know if issue is fixed on your device.

**Comment by Cybermom** [comment]
I'm happy to say that the reported errors have been successfully fixed in the latest version of Ecency!👍Thank you for having me check before closing the ticket.Have a great day!On Aug 10, 2020 2:56 AM, Feruz M <notifications@github.com> wrote:
@Cybermom please check latest update and let us know if issue is fixed on your device.

**Comment by Cybermom** [comment]
One side item to add though, when I tried to delete my saved draft not everything clears out completely. The body of the post is deleted but the title and tags remain. Not a major problem, just annoying to have to delete manually.Thanks!On Aug 10, 2020 3:56 AM, n1haskin@hotmail.com wrote:I'm happy to say that the reported errors have been successfully fixed in the latest version of Ecency!👍Thank you for having me check before closing the ticket.Have a great day!On Aug 10, 2020 2:56 AM, Feruz M <notifications@github.com> wrote:
@Cybermom please check latest update and let us know if issue is fixed on your device.

**Comment by feruzm** [comment]
@Cybermom Can you try this again with 3.0.5 version that we just pushed to PlayStore and AppStore, please? If fixed, we can close this issue.

**Comment by Cybermom** [comment]
Greetings, Feruz! Yes, certainly.I will verify and advise.👌On Oct 16, 2020 3:10 AM, Feruz M <notifications@github.com> wrote:
@Cybermom Can you try this again with 3.0.5 version that we just pushed to PlayStore and AppStore, please? If fixed, we can close this issue.

**Comment by Cybermom** [comment]
Unfortunately the bug still exists.

**Comment by feruzm** [comment]
Thank you, perhaps once of the latest improved introduced bug, we will check!

**Comment by feruzm** [comment]
Could you please recheck with v3.0.11? Thank you!

**Comment by feruzm** [comment]
Could you please recheck with v3.0.14?

**Comment by Cybermom** [comment]
Yes. Do you have a link to the original bug/ticket please? Thank you!On Feb 5, 2021 2:45 AM, Feruz M <notifications@github.com> wrote:
Could you please recheck with v3.0.14?

**Comment by feruzm** [comment]
Yes, it is here: https://github.com/ecency/ecency-mobile/issues/1750

**Comment by Cybermom** [comment]
Perfect! I know the issue was fixed and was working fine for sometime. I haven't been posting as much as I'd like in recent months. I will create a new post and verify if all is A-okay so the ticket can be closed.Love the new release!!!♡💯♡On Feb 5, 2021 4:24 AM, Feruz M <notifications@github.com> wrote:
Yes, it is here: #1750

**Comment by feruzm** [comment]
ok, thanks! We can reopen this or create new ticket if issue persist or something new comes up. I will close this one for now, feel free to leave a comment after your tests.

**Comment by Cybermom** [comment]
Sounds like a plan! I'll definitely play around with Ecency over the weekend and note any irregularities. Have a terrific Friday!On Feb 5, 2021 5:59 AM, Feruz M <notifications@github.com> wrote:
ok, thanks! We can reopen this or create new ticket if issue persist or something new comes up. I will close this one for now, feel free to leave a comment after your tests.
