### ISSUE TITLE
Android image selection gallery coloring check

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1829]
In some android image selection for upload shows dark unreadable text colors.
https://ecency.com/hive-125125/@steemseph/ecency-bug-photo-gallery-folder

another related report: https://ecency.com/hive-125125/@iliyan90/re-ecency-2021118t122524674z

**Comment by kilicfurkan** [comment]
I'll add this line to the Podfile.
`pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop picker/ios/QBImagePicker/QBImagePickerController.podspec'`

https://github.com/ivpusic/react-native-image-crop-picker/issues/1202

**Comment by feruzm** [comment]
I don't think this is needed, this is Android issue, not iOS.

**Comment by kilicfurkan** [comment]
Gallery photo seems like iOS 🤔  I tought it was iOS

**Comment by feruzm** [comment]
ok, we will check with user after 3.0.13 release, this can stay open for now.
