### ISSUE TITLE
Filters font width check

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#1830]
There is weird bug reported by one user, check this and make sure we have a fix.
![image](https://user-images.githubusercontent.com/3015990/105183933-7178c080-5b37-11eb-9321-da0f0f3c230d.png)

Device details:

![image](https://user-images.githubusercontent.com/3015990/105488398-38b52480-5cba-11eb-8553-8312041b6b4a.png)

**Comment by kilicfurkan** [comment]
Seems it is related to this bug. 
https://github.com/facebook/react-native/issues/15114
Some OnePlus and Oppo phones cut the last letter of the word which is in 'bold' style. I'll add one letter space before and end of the word. Probably, this will fix the problem.
