### ISSUE TITLE
Favourites album unavailable while picking images on iOS

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1867]
Another report if you can take a look, user reporting they cannot see images from their favorites list or album, when upload

**Screenshot**
https://cdn.discordapp.com/attachments/808287446948249632/822874474105405491/image0.png

**Comment by noumantahir** [comment]
Fixed: user now have access to Favorites. album from image picker... there are whole lot of options we can opt for on iOS, use this link below to see if we need to add more albums as selection.

https://github.com/ivpusic/react-native-image-crop-picker/blob/master/README.md#smart-album-types-ios

**Screenshot**
![IMG_E37158A9F629-1](https://user-images.githubusercontent.com/6298342/111991302-f97a4700-8b35-11eb-8a41-7f6e2938c897.jpeg)

@feruzm

**Comment by feruzm** [comment]
@noumantahir super, let's disable videos for now 😄  I noticed few people attempt to upload videos even if our backend doesn't fully support it. It allows upload which we will fix soon, but UI side could also don't show videos.

**Comment by noumantahir** [comment]
yes, we can remove Videos from list of albums.
