### ISSUE TITLE
Profile cover image not expanding to full width

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1868]
Another bug: profile cover image style has changed for some reason not full width

**To Reproduce**
1. Go to Profile screen for @ecency as sample

**Expected behavior**
Cover photo should cover all width

**Screenshots**
![779495CB-0C83-49CB-894C-B3152FBCDBE1](https://user-images.githubusercontent.com/6298342/111970238-e5761b80-8b1c-11eb-8d23-743b76293ce5.png)

**Comment by noumantahir** [comment]
Initialling debug did not reveal any issue with <Image component itself thogh it was missing a resizeMode.. 

updated resize mode and changed component from built in <Image to <FastImage 

![Screenshot 2021-03-22 at 5 19 24 PM](https://user-images.githubusercontent.com/6298342/111988809-c97d7480-8b32-11eb-9c51-c4a4a1d338c0.png)

**Comment by feruzm** [comment]
@noumantahir ok, let's test it out and see if that resolves the issue.
