### ISSUE TITLE
Infinite scroll not working for some communities

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1869]
For some communities infinity scroll do not update list of posts from that community.

1. Go to search
2. Search for Shadow hunter
3. In shadow hunter profile scroll down to bottom
4. New posts will not loaded

**Expected behavior**
Infinity scroll should work as expected for all posts lists pages.

**Smartphone (please complete the following information):**
Affecting devices and versions.

**Additional context**
In my initial testing, it seems request for new posts is being made as expected, last permlink and auth id is passed unto get posts request however the returning list contains the same old list of posts.

Given these results, it is either an issue with class initiating the network request, or directly an issue with backed. require more testing to verify observations though.

**Comment by noumantahir** [comment]
New findings regarding this issue...if we only change the sort type, the infinite scroll starts working just fine.

The query below works fine for Shadow Hunters group, but malfunctions when sort is set to trending

![Screenshot 2021-03-22 at 8 10 37 PM](https://user-images.githubusercontent.com/6298342/112012064-b080bd80-8b4a-11eb-8ea7-5c30176ec34a.png)

**Comment by feruzm** [comment]
@noumantahir on website, it works fine... https://ecency.com/trending/hive-179017

i think it is not backend issue, but somewhere in code we have logical issue perhaps.

**Comment by feruzm** [comment]
#1871 fixes this as well
