### ISSUE TITLE
Replace postcard touchable opacity with no feedback touchable

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1873]
Every once in a while when scroll while tapping directly on a post image, it creates a flashy effect of changing view opacity and then discard the touch event in favour of scroll, this creates a somewhat annoying experience for user..

tapping on a post image to open detail is more or less a second nature for a regular social media consumer, I would say it safe make the tap with giving feedback to user... even facebook do use no tap feedback approach.

Steps to reproduce the behaviour:
1. Go to feed
2. Tap down on post image 
3. Start scrolling without lifting your finger
4. You will experience a flashy effect before scroll

**Screenshots or Video**

https://user-images.githubusercontent.com/6298342/112035626-8d153d00-8b61-11eb-882a-d32e5d49c6a1.mov

**Comment by feruzm** [comment]
yes lets do it!
