### ISSUE TITLE
Native filter tabs

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1888]
Current filter system is used more like button to shift state causing posts feed to re-render posts list items. This causes a momentary lag in app performance.

**Expected behavior**
The transition from one tab to another should be instantaneous. just like bottom navigation tabs only in this case it should change posts filter.

**Additional context**
The idea is to replace button based filter tab with actual native tabs with built-in cache functionality. 

Ideally the new system will use most of the same codebase as available postsContainer and sub components

**Checklist**

- [x]  promoted posts
- [x]  user switching hooks - (buggy when switching user while in non feed tab)
- [x]  double tap to scroll up
- [x]  load posts from storage on startup
- [x]  handling logout
- [x]  Make hide Images button functional
- [x]  scheduled new posts check
- [x]  Fix memory leak on component unmount
- [x]  fix missing keys issues
- [x]  traverse on scroll event back to component parent
- [x]  post tabbedPosts to profile screen
- [x]  port tabbedPosts to community pages
- [x]  port tabbedPosts to tag results pages

**Comment by noumantahir** [comment]
A quick status update regarding native filters...

So far we have,
 - Implemented basic tabs with clean filter change implementation.
 - Ported load posts routine to it's separate sub-class under `tabbedPosts`
 - Ported our reducer as it is from postsContainer and organised it better along with some cleaning.
 
Only drawback we have in our current implementation is the fact when a list is updated, the chagne is not register thrown by reducer, to make it force throw a change callback, I am copying state `Object.create(state)` and returning it back, not the most efficient solution but is done only for experimentation for now.

Status Update Log 
https://user-images.githubusercontent.com/6298342/113621976-cb3c5180-9675-11eb-9e2a-277a0a0a3b4a.mov

The recording is from an android phone running in debug mode, release mode performance will be even better for sure.

**Comment by noumantahir** [comment]
**Status Update**
The feed screen is now useable with most of primary functions like, 

1. pagination
2. refresh
3. logged out view
4. empty list view for friends and communities tabs

Pending Items
1. promoted posts
2. user switching hooks
3. double tap to scroll up
4. new posts check

Video
https://youtu.be/ZDgcxsvxw-k

**Comment by noumantahir** [comment]
@feruzm please if you get a change feel free to update the ToDo/Pending items to list of feed screens functionalities... it's a big component, very easy to miss something from tests.

**Comment by noumantahir** [comment]
@feruzm checkout this issue related to promoted posts fetch on tab change...there is a glitch when new promoted posts is rendered in place of previous post because of image height calculation. this should affect our previous builds as well...

However if user move to other tab for the first time, the glitch do not affect anything as expected.

https://user-images.githubusercontent.com/6298342/114015269-efb94900-9882-11eb-8999-d1fb3ea0cd94.mov

**Comment by noumantahir** [comment]
Suggestion 1:
we keep the current structure but fix height of promoted post, it will remove the glitch in no time.

Suggestion 2:
we fetch updated promotions on list end callback and stack promoted posts just like regular posts.

**Comment by feruzm** [comment]
@noumantahir
1. You mean have fixed size for height of promoted posts?
2. You mean on first list end callback we show all promoted posts? Promoted posts should be showing every 3 item on list, so right now limit 20 means we should have at least 6 promoted post until first list end callback.

**Comment by noumantahir** [comment]
@feruzm 
1. yes
2. if we remove refresh ads on tab change, we will have same old list of ads, what I am suggesting is we add more ads to promotedPosts array when all ads are displayed so user see new ads as scrolling down instead of not showing at all

**Comment by noumantahir** [comment]
Status Update

- [x]  1. promoted posts
- [x]  2. user switching hooks - (buggy when switching user while in non feed tab)
- [ ]  3. double tap to scroll up
- [ ]  4. new posts check
- [x]  5. load posts from storage on startup

**Comment by noumantahir** [comment]
**Updates**

- [x]  promoted posts
- [x]  user switching hooks - (buggy when switching user while in non feed tab)
- [ ]  double tap to scroll up
- [x]  load posts from storage on startup
- [x]  handling logout
- [x]  Make hide Images button functional
- [x]  scheduled new posts check
- [x]  Fix memory leak on component unmount
- [x]  fix missing keys issues
- [ ]  post tabbedPosts to profile screen
- [ ]  port tabbedPosts to community pages
- [ ]  port tabbedPosts to tag results pages

**Comment by noumantahir** [comment]
**Updates**
- [x]  port tabbedPosts to community pages
- [x]  port tabbedPosts to tag results pages

**Pending**
- [ ]  post tabbedPosts to profile screen - scroll issues, tab change issues

**Comment by noumantahir** [comment]
attempting to make use of this package... 

https://github.com/zyslife/react-native-head-tab-view

**Comment by noumantahir** [comment]
skipping head-tab-view for now, documentation is very confusing and is not well written package

**Comment by noumantahir** [comment]
- [x]  port tabbedPosts to profile screen
 
 Know issues
 - tab change issue while scrolling

**Comment by noumantahir** [comment]
Finally! fixed weird unresponsive tab change while scrolling issues by discarding nested scrollview in favour of stacked tab bars.

The final implementation is surprisingly more clean may even be more efficient as there are not nested tab bars. 

Only thing I dislike the fact there are 2 tabs for each stack when viewing your own profile, that does not look as promising compared to 3 - 2 stacked tabs


https://user-images.githubusercontent.com/6298342/114520188-9b371480-9c5a-11eb-8925-d4dcadfae5f2.mov

**Comment by noumantahir** [comment]
@feruzm 

**My suggestion:**
We can do non stacked 3 tabs [Posts, Blogs, Replies] for user's profile and keep other profile stacked..

**Comment by feruzm** [comment]
@noumantahir lets move Blog to 1st line of tabs and remove sub tabs ? My only concert is that, can these tabs if 3-4 items fit nicely in smaller screen sizes. We can of course make Wallet tab as icon so it takes lesser space when viewing other people's account.

**Comment by noumantahir** [comment]
let me try.. we can also try removing image icon perhaps... we already have images toggle button in feed screen

**Comment by feruzm** [comment]
good point, on profile page that's (view change toggle) probably not necessary

**Comment by noumantahir** [comment]
@feruzm single profile tab bar on small to large screens, codes pushed as well..

![Screenshot 2021-04-13 at 2 24 27 PM](https://user-images.githubusercontent.com/6298342/114530116-15b86200-9c64-11eb-9c6e-01bb8ee47863.png)

**Comment by feruzm** [comment]
after update from previous version, I launched app and this is what I got... For example, Top filter at first loaded posts and then showing spinner, it did stop but on other tabs it is not stopping so there is likely some bug or cache update logic that's not working.

https://user-images.githubusercontent.com/3015990/114842475-8c2e9e80-9de1-11eb-9247-4c0867466fc4.MP4

**Comment by noumantahir** [comment]
could be something introduced because editable tag update as it did required tweak to tabbedPost... will debug
