### ISSUE TITLE
misbehaving multiple image uploads

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#1890]
**Describe the bug**
User reported multi selection on image upload doesn't upload them in same order, maybe we can check if we can fix that?

**To Reproduce**
1. Start making a post
2. adding multiple image
3. urls returned will reordered and last url will cut

**Expected behavior**
returning editor text should maintain order of images and correct urls.

**Screenshots or Video**
![Screenshot 2021-04-02 at 5 34 09 PM](https://user-images.githubusercontent.com/6298342/113416612-1f77d500-93db-11eb-9a52-cbddb0256f32.png)

**Additional context**
Initial tests reveal that the async function that is supposed to run iteractly started upload process simultaneously leading to weird returned texts

**Comment by noumantahir** [comment]
@feruzm any ideas why do we have to update text and selection this way using setNativeProps... this is part of the problem of text getting clipped... not an urgent query, that is putting it in this thread

![Screenshot 2021-04-02 at 6 58 27 PM](https://user-images.githubusercontent.com/6298342/113422239-c5c8d800-93e5-11eb-9fb1-a6479a0cca98.png)

**Comment by noumantahir** [comment]
Findings so far... 

it seems the order is changed before image picker response is received.... our app is no manipulating the order

**Comment by noumantahir** [comment]
This is another issue, the three images are uploaded together, while third one rendering after text.

![Screenshot 2021-04-02 at 8 42 47 PM](https://user-images.githubusercontent.com/6298342/113432885-9d49d980-93f7-11eb-847e-22cefcfe42f3.png)

**Comment by noumantahir** [comment]
Regarding order of image... it gets messed in array we receive from ImagePicker

![Screenshot 2021-04-02 at 8 14 24 PM](https://user-images.githubusercontent.com/6298342/113433495-c0c15400-93f8-11eb-864a-d63d360fda93.png)
![Screenshot 2021-04-02 at 8 16 19 PM](https://user-images.githubusercontent.com/6298342/113433496-c1f28100-93f8-11eb-8943-ee35b82661e0.png)

**Comment by feruzm** [comment]
Let's do modal like bottom sheet list of uploaded images in horizontal bar and user can tap on them to insert at any place they want by moving cursor. Do you think, it is possible?

**Comment by noumantahir** [comment]
We should be able to use this as a goto option...

https://www.npmjs.com/package/react-native-draggable-flatlist

**Comment by noumantahir** [comment]
For a more custom solution, we can try managing uploads. User can drag and place in editor where ever required...

But is more complex to implement

**Comment by feruzm** [comment]
yeah too complex solutions are not worth it, because it is rarely used feature, if we were instagram this would make sense, but for blogging, in rare occasion images are uploaded all at once. Simplest and easiest solution would be good for now.

**Comment by noumantahir** [comment]
Just clicked another simple solution.... Perhaps it was what you were actually referring to....

1. Image button opens horizontal list of uploaded images for the post
2. User has option to add more images to list
3. User may tap on any image and it would be added in place of current cursor position

Backend requirement.
1. We will have to add a media array section in draft table, so user can use different device to refer uploaded media of not already added to post body.

Later we can upgrade this to have drag and drop function

**Comment by feruzm** [comment]
For that we already have backend/api, we call it user image gallery, every upload of user is saved into that db. Check website, we already utilize that there, we can do in mobile app too like snippets 👍

**Comment by noumantahir** [comment]
Any api reference available for gallery...I believe this is a must have feature in mobile side as well.
