### ISSUE TITLE
Couldn't find GoogleServices.json and GoogleService-Info.plist in the ios directory

### ISSUE THREAD

**Issue by dibakar95** [ecency/ecency-mobile#2055]
**Hi,** 
I just cloned the project and want to give it a try, I was facing some issues at initial setup. I found that googleservices JSON and  Info.plist files were missing as they were added to .gitIgnore. 
May I know how can I get through this?
Any help is highly appreciated.
Thanks in advance.

**Comment by feruzm** [comment]
@dibakar95 👋 

You will have to create firebase project and use your own json files, it will be provided by google firebase, those are used for notifications.

**Comment by dibakar95** [comment]
@feruzm thanks a lot. I will try this. Closing this issue.
