### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by unklebonehead** [ecency/ecency-mobile#2093]
**Describe the bug**
While trying to full screen a 3Speak video and rotate to landscapt to view app freezes with only Ecency logo showing. Locks phone up and required a soft reboot to fix.

**To Reproduce**
While watching a 3 Speak video tap the full screen icon and turn phone to landscape. (On it's side)

**Expected behavior**
Expected to be able to watch 3Speak video full screen.

**Screenshots or Video**
Unable to get screenshot due to phone frozen..

**Smartphone (please complete the following information):**
 - Device: OnePlusOne 6T
 - OS: OxygenOS (OnePlusOne Android)
 - Version 10.3.12 (Android 10)

**Additional context**

Can provide logs if you need.

**Comment by aliseyalvi** [comment]
currently landscape is not supported in ecency. Landscape support needs to be added to fully support the fullscreen videos in landscape.
