### ISSUE TITLE
Bug: Youtube embed landscape

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2128]
In ecency app i cannot look yt -video in landscape. If i select full scren and flip my mobile ecency restarts. Is thus known issu?

Galaxy S21 5G,  Android 11

**Comment by aliseyalvi** [comment]
Issue is due to landscape support is not yet added in ecency. We would have to support landscape step by step just like we have added support for RTL languages.

**Comment by aliseyalvi** [comment]
duplicate issue. Refer here https://github.com/ecency/ecency-mobile/issues/2093#issuecomment-1065894479
