### ISSUE TITLE
Improve: Delegation screen

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2158]
Delegation screen uses slider, instead offer input so people can define exact amount.

**Comment by noumantahir** [comment]
@feruzm 

Perhaps we can take design inspirations from other transaction related app, like bank transfer... Also how about having both options, a slider beside amount input, that would also give user a visual perspective of how much he is delegating....

**Comment by noumantahir** [comment]
We can also further improve this experience by making is step wise... select recipient then select amount, review and confirm.

**Comment by feruzm** [comment]
@noumantahir Steps approach I like, it is guided and simple.
