### ISSUE TITLE
Post editing improve

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2165]
Post editing should allow thumbnail changing, but nothing else is changeable after publish.

**Comment by noumantahir** [comment]
@feruzm  I think it is already supported, is it malfunctioning?

![Screenshot 2022-01-29 at 2 37 16 AM](https://user-images.githubusercontent.com/6298342/151624983-b8fa198c-7f74-4b73-b834-5bbf1803676f.png)

**Comment by feruzm** [comment]
@noumantahir melinda earlier reported similar issue, looks like it was image link issue... 👍
