### ISSUE TITLE
[BUG] Comment delete failure

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2168]
**Describe the bug**
While trying to delete multiple comments comment_cashout error appeared on deleting about 5th comment.

**To Reproduce**
1. Go to post comments with a number of your comments
2. Click on delete for each
4. Delete fails after a few deletions

**Expected behavior**
There should be a user friendly way to representing the rejection.

**Screenshots or Video**
![Screenshot 2022-01-29 at 2 45 40 PM](https://user-images.githubusercontent.com/6298342/151656271-6081ae10-eeb0-48a1-a1cc-30ddaf638a4c.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.0
 - Version: 3.0.26

**Comment by feruzm** [comment]
@noumantahir that usually means cashed out comment and posts are not possible to delete. Only when comment/post has negative net_rshares and no replies and before payout/cashout, any of them false won’t allow delete. We need to add that logic and show button only if condition is satisfied for better UX, we have it on vision.
