### ISSUE TITLE
Feature: wallet redesign

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2174]
- [x] assess coin gecko api
https://www.coingecko.com/en/api/documentation

- [x] package for chart
- [x] assess/sandbox test api calls involved in wallet
- [x] wallet main screen components
- [x] wallet details screen components
- [x] make filters functional
- [x] integrate wallet actions
- [x] add missing balances (if HIVE or HBD is pending conversion or reserved in market open orders, etc.) We should still show them and inform people about their other/pending/locked balances. On website, we recently added those, HBD if being converted, it takes 3 days to convert and HBD locked during that time. If HIVE or HBD sell/buy order created (not full-filled by market orders yet, then It is locked as well) When HBD/HIVE being withdrawn from Savings, it takes 3.5 days also locked, etc. etc.

**Comment by noumantahir** [comment]
- [ ] Handle first wallet data load, right now it show invalid data across various cards
