### ISSUE TITLE
Bug: Community subscribe failure

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2209]
User Report
Hey @good-karma a friend of mine is fresh in Hive. He is using the ecency mobile app and tries to join communities but it shows us "Subscibe Failed"

Remarks:
We have received similar reports before as well but we were unable to recreate the issue locally. perhaps we need more details as from which page the user tried subscribing... Communities posts tab, communities list accessed from side drawer, community page etc.  

Ref:
https://discord.com/channels/385034494555455488/385448634197737484/938677741023277137

**Comment by feruzm** [comment]
@noumantahir I did fix it few days ago: https://github.com/ecency/ecency-mobile/commit/6c82ec997ad5f7dc1ce4bb0368b6ce670b6bdb2e
