### ISSUE TITLE
Bug: 3 dot misaligned

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2221]
3 dot misaligned when hidden comment https://media.discordapp.net/attachments/920267778190086205/952633673600073831/image0.jpg

**Comment by aliseyalvi** [comment]
@feruzm 3 dots should be vertically aligned?

**Comment by feruzm** [comment]
@aliseyalvi you see it should be at the end of line, far right side just like other comments. Please check other comments and see if you can replicate
