### ISSUE TITLE
Bug: table view

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#2222]
Bug: table view https://ecency.com/hive-125125/@zakludick/mobey-ludick-household-hive-progress-9e9dfdb7ce598

**Comment by noumantahir** [comment]
Current table behaviour is default by render-html, first I am trying a plugin, if that does not work will think of something else...

Trying this...
https://www.npmjs.com/package/@native-html/table-plugin

**Comment by noumantahir** [comment]
@feruzm this is something we can further work on... that being said... we will lose some of customisation with did with rendering images inside table cells.

https://user-images.githubusercontent.com/6298342/158122303-d89b03e4-e217-4b56-a9f7-e8a4054bd88c.mov

**Comment by noumantahir** [comment]
hmmm... it will open more issues then solving i guess.... 

Plugin implementation
https://user-images.githubusercontent.com/6298342/158123621-65c6965c-fd31-490d-bbdd-a27c496c6b39.mov

Current implementation
<img width="283" alt="Screenshot 2022-03-14 at 12 20 40 PM" src="https://user-images.githubusercontent.com/6298342/158123607-1250bde0-53a2-4c25-8804-0c7b69f1f847.png">
