### ISSUE TITLE
wrong table rendering..

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2292]
https://ecency.com/hive-193552/@gregory-f/actifit-gregory-f-20220509t012149809z

Screenshot
![Screenshot 2022-05-09 at 2 05 32 PM](https://user-images.githubusercontent.com/6298342/167377610-c4e8e249-998e-4bcf-985d-69282842550c.png)

**Comment by noumantahir** [comment]
@feruzm table is formatted in a way that header image is part of first row of columns and phone side html renderer reads that as first column instead of header.... web side however seems successfully distinguish well...

We cannot fix this issue on app side without changing the table html, which is not practical.... 
so our viable solutions are.

1. Either we can fix such behaviour by updating RenderHTML component 
2. or use WebView for rendering tables, though we will lose of functionality that we gained with native rendering like image resizing etc.

![Screenshot 2022-05-09 at 4 31 31 PM](https://user-images.githubusercontent.com/6298342/167401736-a8706000-4bbd-4ee4-8920-1e26b1b05af9.png)

**Comment by noumantahir** [comment]
There is one hack I can try, but it would not be solution in any way... we can check if post is from Actifit, and customise the table format to something that RenderHtml can easily interpret.

What we will have to do is turn this stranding image item into a first row for table.
<img width="1020" alt="Screenshot 2022-05-10 at 9 47 33 PM" src="https://user-images.githubusercontent.com/6298342/167680995-aa556e13-fe80-4772-8eca-77635f016b0d.png">

**Comment by feruzm** [comment]
> There is one hack I can try, but it would not be solution in any way... we can check if post is from Actifit, and customise the table format to something that RenderHtml can easily interpret.
> 
> What we will have to do is turn this stranding image item into a first row for table. <img alt="Screenshot 2022-05-10 at 9 47 33 PM" width="1020" src="https://user-images.githubusercontent.com/6298342/167680995-aa556e13-fe80-4772-8eca-77635f016b0d.png">

If this is viable, I mean if they are consistently same formatting then yes I would agree, doing this minor tweak on actifit posts might do the job

**Comment by noumantahir** [comment]
> > There is one hack I can try, but it would not be solution in any way... we can check if post is from Actifit, and customise the table format to something that RenderHtml can easily interpret.
> > What we will have to do is turn this stranding image item into a first row for table. <img alt="Screenshot 2022-05-10 at 9 47 33 PM" width="1020" src="https://user-images.githubusercontent.com/6298342/167680995-aa556e13-fe80-4772-8eca-77635f016b0d.png">
> 
> If this is viable, I mean if they are consistently same formatting then yes I would agree, doing this minor tweak on actifit posts might do the job

giving it a shot
