### ISSUE TITLE
Implement gallery

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-mobile#236]
Gallery feature is all images user uploaded using eSteem apps, will be getting list of links and show them as gallery, remove and copy link of image so user can include inside post. This page will be accessible from Editor as well

**Comment by ue** [comment]
@fildunsky Could you please prepare a design for that.

**Comment by fildunsky** [comment]
Hmm... maybe just simple/native gallery look? I can make any mockup but what if it will be faster to use already made framework or library on that? Just standard squares for images and option to remove or select them?

**Comment by feruzm** [comment]
@fildunsky this is internal Gallery feature, where user's uploaded Media files will be shown inside app. So can be used for easy copy paste, or delete, etc. Photos/Pictures, Video, Links, etc. @talhasch had some ideas on Media feature, please loop in with him.

**Comment by fildunsky** [comment]
Yes, I see... I just thought maybe it will be a pain for guys to recreate it from scratch from my mockups but maybe here we will start vice vera. If we will take ready made cool library for that (if there are any) and then I will tweak it's look to make it better. How about this?

**Comment by feruzm** [comment]
Gallery will have list of Files (images, videos) And their links can be copied for re-use and links to files can be removed from eSteem collection (initially we will parse those from Steem for user's convenience). We might put it in User's Profile page. 

Similar feature can be found on Twitter (not exact but close enough to illustrate the meaning):

![image](https://user-images.githubusercontent.com/3015990/51750937-3a908100-20bc-11e9-9216-861338368105.png)
