### ISSUE TITLE
Show upload progress modal while uploading images in editor during  post creation process

### ISSUE THREAD

**Issue by aliseyalvi** [ecency/ecency-mobile#2430]
Suggestion From Nouman: Add image thumbs as placeholder in images modal with activity indicators/progress

- [x] add basic upload function
- [x] update UI
- [x] update and test new selection and upload methods
- [x] fixed isUploading state causing glitch during multiple uploads
- [x] allow inserting images without losing editor focus and keyboard
- [x] include delete feature
- [x] test deep link media insertion

**Comment by noumantahir** [comment]
Current implementation of media insertion is more intrusive than it has to be... below is my suggestion to improve that behaviour. a media section that would appear on media insert button click, but will not obstruct user's flow on editing post, user can easily change input points and insert images with single tap

![Screenshot 2022-09-01 at 4 44 35 PM](https://user-images.githubusercontent.com/6298342/187907207-7b435b34-4676-490d-bcbb-be36b4a44c37.png)
