### ISSUE TITLE
BUG: android app installed on chromebooks not rendering properly

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2449]
Happens when opening app using an external post link.

![Screenshot 2022-09-07 at 7 50 26 PM](https://user-images.githubusercontent.com/6298342/188909152-1474b58a-d4c4-413c-8127-5e7c761959fc.png)

Issue might be due landscape/portraint width not calculating properly. Need to reproduce it first

**Update:**
Attempted to reproduce this issue on android table emulator, apparently it is not being reproduce even if we open Ecency app while tablet is locked in landscape mode.

![Screenshot 2022-09-23 at 5 19 12 PM](https://user-images.githubusercontent.com/6298342/191958607-d8987975-87e7-4d71-91da-cc9c5aaaaf5c.png)

If we notice closely look at the first screenshot shared by melinda, the **BasicHeader** dimensions are being read properly but it messes up as it renders **PostBodyView**. Based on this deduction, the issue seems to be coming from this code linked below, it is just a guess though
https://github.com/ecency/ecency-mobile/blob/development/src/utils/getWindowDimensions.ts#L18

**Comment by aliseyalvi** [comment]
@noumantahir issue needs more brainstorming and according to my assesment we have to support landscape mode because forcing portrait is not a good solution and it is causing issues or various devices like android tablets with width greater than height and when starting app in landscape mode locked
