### ISSUE TITLE
Implement useQuery

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2483]
Extend useQuery to notifications, snippets and images.

**Comment by noumantahir** [comment]
@feruzm need some suggestions...

I was experimenting with useQuery for couple of days, drafts with useQuery worked really, the built-in native support for infinite scroll seems to be written purely for react.js and did not consider use case with react-native. 

![Screenshot 2022-09-23 at 4 21 55 PM](https://user-images.githubusercontent.com/6298342/191950032-6ea403cd-4f76-4e90-93af-34c2a24fba99.png)
ref: https://github.com/TanStack/query/discussions/1275

Though the behaviour can be fixed with some tweaking, but while for solutions I can realised since we are already using redux the RTK query can also give similar results without adding much package load to the app itself.

The con however is that, RTK query structure is still require more learning compared to useQuery's clean and simple implementation. But the benefit would be that our cache and global state will be managed purely by redux only, so we would not have to manage multiple packages in same app and obviously redux almost always consider react-native as use-case

![Screenshot 2022-09-23 at 4 25 08 PM](https://user-images.githubusercontent.com/6298342/191950578-c1accf71-07e5-453b-822e-d5b5bf7db7d2.png)
![Screenshot 2022-09-23 at 4 24 55 PM](https://user-images.githubusercontent.com/6298342/191950582-7bbaf402-33d5-4b05-9545-46f489097b2e.png)


One to one comparison chart
ref: https://redux-toolkit.js.org/rtk-query/comparison#comparing-feature-sets

**Comment by feruzm** [comment]
@noumantahir If react-query (useQuery) is simpler to use and does what we need it for, then I think we can stick to that, we don't know how RTK will solve infinite scroll feature which is not out yet, as per comparison page and your conversation with dev...right?!

**Comment by noumantahir** [comment]
@feruzm yes, I agree on that part, useQuery is very very simple and clean. infinite scroll is not much of a deal, we are good without it in both RTK and react-query, it was just a realisation that react-native is not much of priority for the package.. as for working side. 

I think it is so far serving good, we can continue with it. RTK's value was because of redux maintaining the ecosystem implemented in our codebase.
