### ISSUE TITLE
Alert.alert with non string argument causing app to crash.

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2535]
Apparently there is some Alert.alert instance in app that is rarely causing app to crash in production, the issue is likely coming because a non string argument is passed to the alert.alert.

bugsnag ref: https://app.bugsnag.com/ecency/ecency-mobile/errors/61096df576a5b40007cffeea?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production

stackoverflow ref: https://stackoverflow.com/questions/52992606/value-for-title-can-not-be-cast-from-readablenativemap-to-string

**Comment by feruzm** [comment]
@noumantahir can we stringify everything, also we should cut string so it won't overflow screen with long and scary text for user.

**Comment by noumantahir** [comment]
> @noumantahir can we stringify everything, also we should cut string so it won't overflow screen with long and scary text for user.

report was not specific, needed digging, but it was easy to find, already fixes the underlying source
