### ISSUE TITLE
Suggestion to change blog post images interaction flow

### ISSUE THREAD

**Issue by noumantahir** [ecency/ecency-mobile#2862]
Right now if user tap on an image in blog user is prompted to chose the action that can be performed instead of opening the fullscreen image preview section that mostly a user would expect considering almost all other social apps offer, and even we offer in waves as well.

What I am suggesting is, we can open image slideshow on image tap, and give user option to download and copy image url as part of the preview section.

This approach does not change the number of taps in case user was intending to download or copy url and also renders preview as first action which generally users are intending to do.

<img width="244" alt="Screenshot 2024-04-23 at 09 59 37" src="https://github.com/ecency/ecency-mobile/assets/6298342/f90dfbcf-e218-4dd8-8a5b-92dcc563f867">
<img width="246" alt="Screenshot 2024-04-23 at 10 00 00" src="https://github.com/ecency/ecency-mobile/assets/6298342/c08a158f-ffac-4a3a-b9e9-236591bd9f64">

**Comment by feruzm** [comment]
@noumantahir I like this approach, let's do it.
