### ISSUE TITLE
Suggestion: Indicate platform author used to publish e.g (eSteem, Dtube, Steemit)

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#363]

**Comment by mistikk** [comment]
@horpeyloaded can you give more information about issue?

**Comment by feruzm** [comment]
It is related to #724 @mistikk

**Comment by mistikk** [comment]
@feruzm can you check this issue

**Comment by feruzm** [comment]
@mistikk it is not same as #724, maybe horpey updated title.
This is about from which app post was submitted. Check surfer 
<img width="780" alt="Screenshot 2019-09-17 at 19 19 39" src="https://user-images.githubusercontent.com/3015990/65060317-5238b480-d980-11e9-8151-1398f2d308e7.png">
<img width="759" alt="Screenshot 2019-09-17 at 19 21 33" src="https://user-images.githubusercontent.com/3015990/65060404-72687380-d980-11e9-935d-901193722f77.png">
It should be simple lines to extract from json_metadata of post and if there is no `app:`, it should just ignore it, if there is app, it should cut text to maximum 15 characters (NB: it shouldn't crash if no app is defined 😄)
