### ISSUE TITLE
Suggestion: Show total RCs effective info (Comments, votes and transfers)

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#375]
Similar to this:
![](https://i.ibb.co/z8rdTxc/Screenshot-2019-01-06-14-46-53.png)

Can we show RCs details (Comments,  votes and transfers) when user tap on the banner image as shown below @fildunsky can provide better UI/UX for this.
![](https://i.ibb.co/kcq9461/Screenshot-2019-01-07-07-09-30.png)

**Comment by fildunsky** [comment]
<img width="375" alt="2019-01-08 14 47 37" src="https://user-images.githubusercontent.com/32987666/50829088-638ee300-1354-11e9-8ea5-e8e57bde94a9.png">

We can show it like this. My thoughts on the issue and design details: https://zpl.io/bAZDAqq

**Comment by mistikk** [comment]
@feruzm how can we calculate to this values?

**Comment by feruzm** [comment]
@mistikk here is rate of each operation
comment    1M
vote    0.066M
transfer    0.17M
