### ISSUE TITLE
Enable footnote option with @fildunsky footers

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#377]
The footnote will be the last line of every post if user enables it. 

We don't need to force our users like other ~app~ Users who are willing to promote or love ❤ eSteem will surely enable it. 

The option can be in `Settings` or `Post page` and be checked by default. 

@fildunsky, how is this?

https://steemit.com/illustration/@dunsky/esteem-surfer-post-footers-designs-fc548f5926431est

**Comment by fildunsky** [comment]
Yes, good to have this as a default option but I would work on the footers more in this case, make it more unified or generic and much smaller size...

**Comment by horpeyloaded** [comment]
Great! Thank you @fildunsky 🙏🙏🙏
