### ISSUE TITLE
[Feature Request] Please add payout section option in esteem v2

### ISSUE THREAD

**Issue by face2face-utopian** [ecency/ecency-mobile#458]
My proposal is to add a useful feature in the esteem mobile v2 so that users can select payout option as per their desire. I was creating a post using v2.0.6 and try to change payout as 100% power up but i did not see any option in app hence please add this feature. The said option was in v1 and also is in esteem surfer.

Please refer to the image also for more clarity. 
![screenshot_20190118-070250_esteem 1](https://user-images.githubusercontent.com/36129744/51360529-09c7af00-1af2-11e9-9d73-ee6734f9052b.jpg)

And below is snap of current version without payout selecting option:

![screenshot_20190118-070425_esteem 1](https://user-images.githubusercontent.com/36129744/51360559-28c64100-1af2-11e9-89d2-f5817c2cb8d4.jpg)

**Comment by feruzm** [comment]
Thanks for reporting @face2face-utopian !
@fildunsky Could you suggest design for Advanced options like this?

**Comment by fildunsky** [comment]
Proposal for `Clear all` https://zpl.io/aXw79JX
