### ISSUE TITLE
Pin Post 📌

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#552]
Hey guys, I have an Idea that you may like it.
It would be great if there was an option so we could pin one of our posts to show it on top of our blog. 
we can use that post as a list, every time we posted something new, edit it and add this new one's link there.

I myself have different categories that I write about it, cars, since, photography,...
It would be better if I could organize them in a list.

Or you can add list to profiles, so when someone stopped by a profile, he can see a list of all the post that user made.
What do you think? Is it possible?

**Comment by feruzm** [comment]
Thanks, it is really good idea... We have extensive version of this that we call, `Featured posts` where you can feature your post on your own profile or on feed. Similar to Promoted post but with internal eSteem token. We will work on that right after our token system is out.
