### ISSUE TITLE
Data saving mode in settings

### ISSUE THREAD

**Issue by horpeyloaded** [ecency/ecency-mobile#732]
I love this feature on eSteem legacy `Compact View` -- this can be called `Data Saving` or `Text mode` in the present version.

When enabled, image thumbnails are not displayed and images in posts are not displayed automatically except when Tab to view. 

This save internet bandwidth for those with limited Data.

<img src="https://i.ibb.co/HxfKynk/Screenshot-2019-03-28-20-59-52.png" alt="Screenshot-2019-03-28-20-59-52" border="0">

**Comment by mistikk** [comment]
We have already a feature for Data Saving on feed screen, maybe we can implement for post details page too in the feature
![Screen Shot 2019-03-29 at 14 43 28](https://user-images.githubusercontent.com/8211075/55230836-08251080-5232-11e9-832b-93a7990606bd.png)

**Comment by horpeyloaded** [comment]
I know, that's not enough because it doesn't work like the **legacy app** and one has to tab that 6-boxes on different opening of the app @mistikk.

Please check the legacy app out with the feature enabled `Compact View` to see what I mean.

Please add it to settings… @feruzm?

**Comment by horpeyloaded** [comment]
I know, that's not enough because it doesn't work like the **Legacy app** and one has to tab that **6-boxes** on the different/each opening of the app @mistikk.

*Please you could check the legacy app out with the feature enabled `Compact View` to see what I mean.*

Please add the option to settings and it should work like what I just described above (Hide post thumbnails and automatically display of images on posts)… 

**Or**
Please make the **6-boxes** save it states for users i.e if enabled it should save the settings in local until users tab again to disable if the `Data Saving` option in Settings will make it look hectic.

**Comment by horpeyloaded** [comment]
Images still show on post when enabled. Please make it not to show any media until the media box is clicked when the option is enabled.
