### ISSUE TITLE
[BUG] esteem v2.1 Long blogs/posts is unable to open as normal blogs;

### ISSUE THREAD

**Issue by peerzadaaabid** [ecency/ecency-mobile#929]
# Project Information

Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

# Expected behaviour

The long  post should have been opened immediately or within 3 -5 secs

# Actual behaviour
Here when I clicked on post it took  time longer time than ormal posts to open.
How to reproduce

1-Download the application
2- Go to the long blog/post
3- Open it and notice the error

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: Note 4

Recording Of The Bug
https://youtu.be/g2Qt-FtmaGM

My Github Account

https://github.com/peerzadaaabid

**Comment by feruzm** [comment]
Thanks for report @peerzadaaabid, we will take a look and improve performance.. 😉 

@ue and @mistikk I think we should check performance of new renderer as well as find way to load portion of post first (as quick as possible) and render other part on scroll to make page more responsive.

**Comment by feruzm** [comment]
@peerzadaaabid if you are still around and using Ecency app, could you check if this issue still exist on Ecency?
We have rebranded to Ecency and did multiple releases, improvements since then. If you see that issues exist, please feel free to reopen or create new issues. Thank you!
