### ISSUE TITLE
[BUG] App crashes when opening it and immediately minimizing it.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [ecency/ecency-mobile#940]
**Describe Bug:**
 I tried to open the app while opening it I minimized it immediately to the home screen. After that, I closed the Mobile Network of my phone and waited for some seconds. Then the app crashed.
**How to reproduce:**
* Download the app.
* Click on it to open and then immediately minimize it. (Showed in the video)
* After minimizing, close the Mobile Network of the phone.
* Wait for few seconds and see the bug.
**Video/Screenshot:**
https://youtu.be/qDQcK9En7qU
**Device:**
* Android: RedMi Y2/S2
* OS: 8.1.0
* App version: 2.1.0

**Comment by feruzm** [comment]
@PeerzadaZeeshan Could you please check this with latest Ecency release? If you still experience this issue, feel free to reopen or create new issues. Thank you!
